{% set version = "0.2.1" %}

package:
  name: cpp_comment_format
  version: {{ version }}

source:
  url: https://github.com/tdegeus/cpp_comment_format/archive/v{{ version }}.tar.gz
  sha256: 7658ae0d669c4c1f4f6dcbe1011925d3c85dadfc7e13afc35f2c1b3e130f8a01

build:
  number: 1
  noarch: python
  script_env: SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - cpp_comment_format = cpp_comment_format:_cli

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=45
    - setuptools_scm >=6.2
  run:
    - python >={{ python_min }}
    - pyyaml

test:
  imports:
    - cpp_comment_format
  commands:
    - pip check
    - python -c "import cpp_comment_format; assert cpp_comment_format.version == '{{ version }}'"
    - cpp_comment_format --version | grep {{ version }}
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/tdegeus/cpp_comment_format
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Format C++ comment blocks.
  description: Format C++ comment blocks.
  doc_url: https://cpp_comment_format.readthedocs.io/
  dev_url: https://github.com/tdegeus/cpp_comment_format

extra:
  recipe-maintainers:
    - tdegeus
